### ISSUE TITLE
Write test case for inventory model to enable inventory serialization and deserialization

### ISSUE THREAD

**Issue by faberald** [Inventory-Squad/inventory#33] opened 2019-10-06 20:32 UTC
**As a** developer  
**I need** test cases 
**So that** I can use TDD workflow to develop the inventory model

**Assumptions:** 
* Test that covers all the test cases related to serializing an inventory object
* Test that covers all the test cases related to deserializing an inventory object

**Acceptance Criteria:**
```
Given a set of tests
When nosesets command is called
Then the tests should run and fail(before finishing the model development)/pass(after finishing the model development)
```

**Comment by joanne3634** [comment] 2019-10-10 05:19
Duplicate of #47

**Comment by joanne3634** [comment] 2019-10-10 05:19
Duplicate of #47

**Closed** 2019-10-10 23:05 UTC
Labels: enhancement
