### ISSUE TITLE
Update README.md 

### ISSUE THREAD

**Issue by eatingzhang0611** [Inventory-Squad/inventory#14] opened 2019-09-27 15:23 UTC
**As a** user
**I need** to instruction to the service
**So that** I would know what calls are available, what is the expected output, and how to run and test the code.

**Assumptions:** 
* The README.md file is well written.
* Markdown is used in the file.

**Acceptance Criteria:**
```
Given I am a user,
When I follow the instructions in the README.md file
Then I would use the service successfully.  
```

**Comment by joanne3634** [comment] 2019-09-30 22:26
duplicate of #17

**Comment by joanne3634** [comment] 2019-09-30 22:27
duplicate of #17

**Closed** 2019-10-16 14:54 UTC
Labels: documentation
